name: Basic CI - Check R Plumber API

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.x' # Or your desired R version

      - name: Install Plumber
        run: R -e 'install.packages("plumber", repos="https://cloud.r-project.org")'

      - name: Run Entrypoint Script (Basic Check)
        run: R -f api/entrypoint.R --vanilla